### ISSUE TITLE
Schematic missing components in SMD ladder.

### ISSUE THREAD

**Issue by jpnielsen** [kassu/kassutronics#5]
On Kassutronics_LadderVCF_docs_v1.1E.pdf

Is it just me who is reading it wrong, or did you forget to add:
**C1, C2, C3, C4, R6 and R7** 
on the alternative transistor ladder ?

I'd like to make some of these for myself with as much SMD as possible.
Thanks you for making your design available.

**Comment by kassu** [comment]
Hi! The connections are marked with net labels: each wire with a label is connected to all other wires with the same label. That is how the alternative transistors are written without duplicating the capacitors and resistors. Hope this clarifies it!
